# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskr < Formula
  desc "Task runner / simpler Make alternative written in Go (forked version)"
  homepage "https://github.com/YOUR_USERNAME/taskr"  # 请替换为您的实际仓库地址
  version "0.1.0"  # 请替换为您的实际版本号
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YOUR_USERNAME/taskr/releases/download/v#{version}/taskr_darwin_amd64.tar.gz"  # 请替换为您的实际下载地址
      sha256 "YOUR_SHA256_FOR_DARWIN_AMD64"  # 请计算并替换为实际的 SHA256

      def install
        bin.install "taskr"  # 假设二进制文件名是 taskr，如果不是请修改
        bash_completion.install "completion/bash/taskr.bash" => "taskr"  # 如果有完成脚本
        zsh_completion.install "completion/zsh/_taskr" => "_taskr"
        fish_completion.install "completion/fish/taskr.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YOUR_USERNAME/taskr/releases/download/v#{version}/taskr_darwin_arm64.tar.gz"
      sha256 "YOUR_SHA256_FOR_DARWIN_ARM64"  # 请计算并替换为实际的 SHA256

      def install
        bin.install "taskr"
        bash_completion.install "completion/bash/taskr.bash" => "taskr"
        zsh_completion.install "completion/zsh/_taskr" => "_taskr"
        fish_completion.install "completion/fish/taskr.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YOUR_USERNAME/taskr/releases/download/v#{version}/taskr_linux_amd64.tar.gz"
      sha256 "YOUR_SHA256_FOR_LINUX_AMD64"  # 请计算并替换为实际的 SHA256
      def install
        bin.install "taskr"
        bash_completion.install "completion/bash/taskr.bash" => "taskr"
        zsh_completion.install "completion/zsh/_taskr" => "_taskr"
        fish_completion.install "completion/fish/taskr.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/YOUR_USERNAME/taskr/releases/download/v#{version}/taskr_linux_arm.tar.gz"
      sha256 "YOUR_SHA256_FOR_LINUX_ARM"  # 请计算并替换为实际的 SHA256
      def install
        bin.install "taskr"
        bash_completion.install "completion/bash/taskr.bash" => "taskr"
        zsh_completion.install "completion/zsh/_taskr" => "_taskr"
        fish_completion.install "completion/fish/taskr.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YOUR_USERNAME/taskr/releases/download/v#{version}/taskr_linux_arm64.tar.gz"
      sha256 "YOUR_SHA256_FOR_LINUX_ARM64"  # 请计算并替换为实际的 SHA256
      def install
        bin.install "taskr"
        bash_completion.install "completion/bash/taskr.bash" => "taskr"
        zsh_completion.install "completion/zsh/_taskr" => "_taskr"
        fish_completion.install "completion/fish/taskr.fish"
      end
    end
  end

  test do
    system "#{bin}/taskr", "--help"  # 假设命令是 taskr --help
  end
end
